server:
  port: 8082
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db_log
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      jdbc-url: jdbc:postgresql://localhost:5433/db_log?currentSchema=medical
      username: postgres
      password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

  liquibase:
    change-log: classpath:/db/changelog.xml
    enabled: true
    default-schema: medical

management:
  endpoints:
    web:
      exposure:
        include: "*"
